language: node_js
node_js:
  - "node"
  - "6"
  - "7"
  - "latest"

before_script:
  - npm install -g gulp
<<<<<<< HEAD
script:
  - gulp
  - npm install
  - npm run coverage
=======
script: 
  - npm install
  - gulp
>>>>>>> updating config files
