language: node_js
node_js:
  - "node"
  - "6"
  - "7"
  - "latest"

before_script:
  - npm install -g gulp
script: 
<<<<<<< HEAD
  - gulp
  - npm install
=======
  - npm install
  - gulp
>>>>>>> invertedIndexClassFunc
  - npm run coverage