language: node_js
node_js:
  - "7"

before_script:
  - npm install -g gulp

script: 
  - npm install
  - gulp run-tests
  - npm run test
  - npm run coveralls

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=o4Q54byGsbo2r7laPPTHtwjEIQDr5BaXK
